name: Detekt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
      - name: Create mock google-services.json
        run: echo "{\"project_info\":{\"project_number\":\"0\",\"project_id\":\"mock\"},\"client\":[{\"client_info\":{\"mobilesdk_app_id\":\"mock\",\"android_client_info\":{\"package_name\":\"com.fern.wallet.debug\"}},\"api_key\":[{\"current_key\":\"mock\"}]}]}" > app/google-services.json
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Detekt
        run: ./gradlew detekt

      - name: Upload Detekt Release report to GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report.html
          path: build/reports/detekt/detekt.html